services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: # hote:container
      - 8080:5173
    volumes:
      - ./client/src/:/app/src/
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports: # hote:container
      - 5050:3000
    volumes:
      - ./server/src/:/app/src/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend:4000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
