FROM node:lts-alpine
WORKDIR /app

RUN apk --no-cache add curl

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install --include=dev

COPY src src
COPY prisma prisma

RUN npx prisma generate

CMD ["npm", "run", "dev"]